// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwSBL4-5JJHIeFvkFKkot_RzQCwhvA7Kg',
    appId: '1:394353534306:web:2b40606c7d96ff0927f83b',
    messagingSenderId: '394353534306',
    projectId: 'shubhamdemy-native',
    authDomain: 'shubhamdemy-native.firebaseapp.com',
    storageBucket: 'shubhamdemy-native.appspot.com',
    measurementId: 'G-NXXWHX2L36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6J93taZDkJ2XQkKrF5ftKje13MiPYHHE',
    appId: '1:394353534306:android:c6d86ca609c9e04327f83b',
    messagingSenderId: '394353534306',
    projectId: 'shubhamdemy-native',
    storageBucket: 'shubhamdemy-native.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8oDEo-jbpm7H11IWl8s8NtjWKb0-cI6Q',
    appId: '1:394353534306:ios:36c918c95f24bb4e27f83b',
    messagingSenderId: '394353534306',
    projectId: 'shubhamdemy-native',
    storageBucket: 'shubhamdemy-native.appspot.com',
    androidClientId: '394353534306-964fbh9gacfqnse5e5de11mfaut6gffe.apps.googleusercontent.com',
    iosClientId: '394353534306-vsdjf66cprijakucfr9iadj7qp5bc8nf.apps.googleusercontent.com',
    iosBundleId: 'com.example.rivaanWhatsapp',
  );
}
